name: Upload
description: Upload artifacts
author: Wilfried Kopp <chevdor@gmail.com>
branding:
  icon: "package"
  color: "green"

inputs:
  aws_access_key_id:
    description: The AWS Key to be used. Make sure it has the required access rights
    required: true

  aws_secret_access_key:
    description: The AWS secret key
    required: true

  aws_bucket:
    description: AWS Bucket
    required: true

  aws_region:
    description: The AWS region
    required: true
    default: eu-central-1

  # TODO
  # public:
  #   description: >
  #     NOT IMPLEMENTED YET
  #     Whether the artifacts should be uploaded as public or not. Please note that some backends do not allow private uploads.
  #   default: "false"
  #   required: true

  mode:
    description: Upload mode. Can be only "standard" for now.
    required: true
    default: standard

  product:
    description: Product
    required: true

  tag:
    description: tag
    required: true

  arch:
    description: arch
    required: false

  file_name:
    description: input file
    required: true

  files:
    description: Description of WHAT to upload
    required:  true

  target_path:
    description: Target path
    required: true

  # TODO
  # labels:
  #   description: >
  #     NOT IMPLEMENTED YET
  #     An array of labels
  #   required: false

  overwrite:
    description: Allows overwriting if the file already exists
    required: false
    default: "false"

  dry:
    description: Will NOT upload the files
    required: false
    default: "false"

  sha256:
    description: Generate a sha256 checksum
    default: "false"

  image:
    description: >
      Docker image to be used. This is usually not something you want to change
      unless you know what you are doing
    required: true
    default: "docker.io/paritytech/releng-scripts"

outputs:
  url:
    description: >
      URL of the uploaded artifact
    value: ${{ steps.upload.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Fetch Docker image
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        docker pull -q $IMAGE
        docker pull -q paritytech/awscli

    - name: Upload ${{ inputs.file_name }}
      id: upload
      env:
        IMAGE: ${{ inputs.image }}
        MODE: ${{ inputs.mode }}
        FILE: ${{ inputs.file_name }}
        FILES: ${{ inputs.files }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_REGION: ${{ inputs.aws_region }}
        AWS_BUCKET: ${{ inputs.aws_bucket }}
        PRODUCT: ${{ inputs.product }}
        ARCH: ${{ inputs.arch }}
        TAG: ${{ inputs.tag }}
        OVERWRITE: ${{inputs.overwrite}}
        DRY: ${{inputs.dry}}
        SHA256: ${{inputs.sha256}}

      shell: bash
      run: |
        . ./action/release/artifacts/upload/lib.sh
        echo "MODE set to $MODE"
        check_mode_inputs $MODE

        show_versions

        main

        check_s3
